CREATE TABLE IF NOT EXISTS users(
   id serial PRIMARY KEY,
   name VARCHAR (50) UNIQUE NOT NULL,
   password VARCHAR (50) NOT NULL,
   email VARCHAR (255) UNIQUE NOT NULL,
   created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
